<?php
/* @var Mage4\StoreLocator\Block\Storelocator $block */
?>

<div id='StoreLocatorMap' class="StoreLocator">
    <h1>StoreLocatore</h1>
    <p class="get_location" style="color:red"> Get Location </p>
    <?php foreach ($block->getStores() as $store): ?>
        <div class="sidebar_left">
            <div class="sidebar_scroll">
                <div class="shop-list stores__list">
                    <ol class="shop-list__list hide-lg">
                        <div>
                            <li class="shop-list__shop flyTo" c>
                                <div class="shop-list__content">
                                    <p class="shop-list__title">
                                        <span><?php echo $store->getName(); ?></span>
                                    </p>
                                    <p class="shop-list__text">
                                        <?php echo $store->getCountry(); ?>
                                    </p>
                                    <p class="shop-list__text">
                                        <?php echo $store->getState(); ?>
                                    </p>
                                    <p class="shop-list__text">
                                        <?php echo $store->getCity(); ?>
                                    </p>
                                </div>
                            </li>
                        </div>
                    </ol>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    <!--    Google_Map-->
    <div className="stores__right">
        <div id="Google_Map">
            Map Right
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
   "#StoreLocatorMap": {
       "Mage4_StoreLocator/js/storelocator": {
            "stores" : <?= $block->getStoresJsonData() ?>,
            "google_api_key" : "<?= $block->getGoogleApiKey() ?>"
       }
   }
}

</script>
